# Generated by Django 2.2.2 on 2019-06-12 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
