# Generated by Django 2.2.2 on 2019-06-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
