# Generated by Django 2.2.2 on 2019-06-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_remove_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seo'),
        ),
    ]
