# Generated by Django 2.2.2 on 2019-06-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_article_seo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='seo',
            field=models.CharField(max_length=100, null=True, verbose_name='Seo'),
        ),
    ]
