# Generated by Django 2.2.2 on 2019-06-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20190613_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read',
            field=models.CharField(max_length=50, null=True, verbose_name='Read'),
        ),
    ]
