# Generated by Django 2.2.2 on 2019-06-13 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_article_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['created_date']},
        ),
    ]
