# Generated by Django 2.2.2 on 2019-06-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20190614_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.CharField(max_length=50, null=True, verbose_name='View'),
        ),
    ]
