# Generated by Django 2.2.2 on 2019-06-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_article_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.IntegerField(null=True, verbose_name='View'),
        ),
    ]
