# Generated by Django 2.2.2 on 2019-06-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20190614_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
